# MAKE SURE THIS MATCHES EXACTLY WHAT APPEARS IN CHAT
# Delete or replace everything here except %player% and %reason%
# Do not include colors like &c or &7.
anti-cheat-alert-format: "Sentinel AC > %player% triggered %reason%"

gui-title: "&4&lFlagged Suspects"
gui-size: 27

lore:
  - "&7-------------------"
  - "&ePing: &a%ping%ms"
  - "&eHealth: &c%health% HP"
  - "&eLast Flag: &c%reason%"
  - "&eViolations: &4%violations%"
  - "&7-------------------"
  - "&aClick to teleport and inspect!"

messages:
  no-permission: "&cYou do not have permission to view flagged suspects."
  teleport-success: "&aTeleported to &6%target% &afor inspection."
  player-offline: "&cThat player is no longer online."
